version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    ports:
      - "3000:80"

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
