server:
  image:
    repository: ozdemiremrah81/server
    tag: latest
    pullPolicy: Always
  port: 5050

client:
  image:
    repository:  ozdemiremrah81/client
    tag: latest
    pullPolicy: Always
  port: 3000

mongo:
  image:
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent
  environment:
    MONGO_INITDB_ROOT_USERNAME: homestead
    MONGO_INITDB_ROOT_PASSWORD: secret
    MONGO_INITDB_DATABASE: simple-69696mern
  volume: mongodata

env:
  REACT_APP_PORT: 3000
  REACT_APP_API_URL: https://16.16.163.150/:5050
  APP_SERVER_PORT: 5050
  REACT_APP_BACKEND_SERVER: http://16.16.163.150:32050/healthcheck