apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  selector:
    app: {{ .Release.Name }}-server
  type: NodePort
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
    nodePort: 32050   # The external port to access the service (must be between 30000-32767)

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
spec:
  selector:
    app: {{ .Release.Name }}-client
  type: NodePort
  ports:
  - protocol: TCP
    port: 80              # External port
    targetPort: 80        # Internal container port
    nodePort: 32000       # The external port to access the service (must be between 30000-32767)

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  selector:
    app: {{ .Release.Name }}-mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # Enforces HTTPS for specified hosts
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # For TLS-enabled hosts
spec:
  tls:
  - hosts:
    - {{ .Release.Name }}.m365.net.tr
    secretName: {{ .Release.Name }}-client-tls
  rules:
  - host: {{ .Release.Name }}.m365.net.tr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-server
            port:
              number: 5050
  - host: {{ .Release.Name }}.m365.net.tr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-client
            port:
              number: 80
