apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  selector:
    app: {{ .Release.Name }}-server
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
spec:
  selector:
    app: {{ .Release.Name }}-client
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000              # External port
    targetPort: 3000      # Internal container port
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  selector:
    app: {{ .Release.Name }}-mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
