name: Cypress Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies for client
      working-directory: ./client
      run: npm ci

    - name: Run Cypress tests
      uses: cypress-io/github-action@v5
      with:
        browser: electron
        working-directory: ./client

    - name: Upload screenshots
      if: always() # Run this step even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: cypress-screenshots
        path: ./client/cypress/screenshots