name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Run specific Cypress test
      uses: cypress-io/github-action@v5
      with:
        spec: client/cypress/integration/endToEnd.spec.js
        browser: chrome
        headless: true
