name: k3s uzerinde dockerize et

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add host key to known_hosts
      run: |
          ssh-keyscan -H ${{ vars.PUBLIC_IP }} >> ~/.ssh/known_hosts
      
    - name: Copy source code to k3s_masternode
      run: |
        scp -i ~/.ssh/id_rsa -r {.,}* ubuntu@${{ vars.PUBLIC_IP }}:/home/ubuntu/app

    - name: Install Docker and Docker Compose on k3s_masternode
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ vars.PUBLIC_IP }} << 'EOF'
          sudo apt-get update -y
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker ubuntu
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        EOF

    - name: Build and deploy Docker Compose on k3s_masternode
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ vars.PUBLIC_IP }} << 'EOF'
          cd /home/ubuntu/app
          docker-compose up -d --build
        EOF