name: Helm Install

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add host key to known_hosts
      run: |
          ssh-keyscan -H ${{ vars.PUBLIC_IP }} >> ~/.ssh/known_hosts
    
    - name: Copy source code to k3s_masternode
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ vars.PUBLIC_IP }} "mkdir -p /home/ubuntu/app" && \
        rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./ ubuntu@${{ vars.PUBLIC_IP }}:/home/ubuntu/app
    - name: Install Helm
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ vars.PUBLIC_IP }} << 'EOF'
          sudo apt update
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

        EOF
    - name: Build and deploy the application
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ vars.PUBLIC_IP }} << 'EOF'
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          cd /home/ubuntu/app/deploy/helm
          helm uninstall vaka1
          helm install vaka1 ./vaka1
        EOF